[build]
# General build options
bin = "bin/task-nexus"                                 # Binary output location
cmd = "go build -o ./bin/task-nexus ./cmd/app/main.go" # Build command
# Full list of files/directories to watch for changes
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["vendor", "bin", "scripts"]
exclude_file = []
# Watching files
watch_dir = ["cmd", "internal", "pkg", "web"]
# Main binary
main = "cmd/app/main.go"

[hotreload]
# Enable hot reload
enable = true

# Specify the delay in milliseconds before reloading after a change
delay = 1000

# Specify whether to show notifications when reloading
notify = true

# Specify the command to restart the server
cmd = "killall -SIGUSR2 {{binary}}"